### ISSUE TITLE
Punto 5. Agregar etiqueta anchor <a> a boton de registro

### ISSUE THREAD

**Issue by JuanChaparroH** [Jose-Moreno/upb-scrum-sprints#1]
### Tareas
+ [x] Implementr un componente de boton con un id `btn_Registro` que se comporte como un hipervínculo (debe anidarse dentro de etiqueta `<a>`
  + [x] Asigne un atributo `id` a la etiqueta `<a>` con el valor **`“link_Registro”`**
  
**Edit**: Originalmente la solicitud estaba como _Agregue una etiqueta `<a>` al componente de boton `btn_Registro`_ pero se cambio despues de inspeccionar de cerca los requerimientos.

### Resultado esperado
El usuario será redirigido a la página de registro de usuarios al hacer click sobre el botón de registro.

**Comment by Jose-Moreno** [comment]
@JuanChaparroH Hola que tal revisando el archivo de index.html se evidencia que la implementación actual del botón es que la etiqueta de boton tiene dentro la etiqueta de anchor (`<a>`) sin embargo se sugiere cambiar el orden y disponer el componente `<button>` dentro de la etiqueta `<a>` ya que el requerimiento espécifico es que al presionar el botón de **registro** nos envie al formulario, pero como está actualmente solo si presionamos el texto **_"Registrese"_** es nos envia al formulario.
