### ISSUE TITLE
Punto 10. Agregar Boton para enviar formulario

### ISSUE THREAD

**Issue by juandavido92** [Jose-Moreno/upb-scrum-sprints#12]
### Tareas
+ [x] Agregar etiqueta `button`
  + [x] Agregar a la etiqueta `button` el atributo `id` debe ser `btn_registrar_usuario`

### Resultado esperado
Debe haber un botón para enviar el formulario, su id debe ser btn_registrar_usuario

**Comment by Jose-Moreno** [comment]
Implementado en c8e10ab17071ee112a9af3808bce147e3d96a304
