### ISSUE TITLE
Punto 3. Incluir logo en la barra de navegación

### ISSUE THREAD

**Issue by jcsabogal** [Jose-Moreno/upb-scrum-sprints#3]
### Tareas
+ [x] Agregar etiqueta de imagen `<img>`
  + [x] Asignar atributo `id` con valor **`“logo_navbar”`** a etiqueta de imagen
  + [x] Asignar el atributo `src` con valor "img/logo.png"

### Resultado esperado
Dentro de la barra de navegación debe haber un logo pequeño alusivo al proyecto. Para esto utilice la etiqueta <img> cuyo atributo id debe ser “logo_navbar”

**Comment by Jose-Moreno** [comment]
Implementado en f442dd0a2cb301eb59b6274a84c6b3b5e1f4883e
