### ISSUE TITLE
Punto 4. Agregar botón para ir a página de registro

### ISSUE THREAD

**Issue by jcsabogal** [Jose-Moreno/upb-scrum-sprints#4]
### Tareas
+ [x] Agregar etiqueta `<button>`
  + [x] Asignar atributo `id` con valor `“btn_Registro”`

### Resultado esperado
En la barra de navegación se agrega un botón para que el usuario pueda ir a una página de registro. Utilice la etiqueta cuyo atributo id debe ser “btn_Registro”.

**Comment by Jose-Moreno** [comment]
Implementado en f442dd0a2cb301eb59b6274a84c6b3b5e1f4883e

**Comment by Jose-Moreno** [comment]
@JuanChaparroH Hola Juank, revisando el boton el atributo `id` está como `btn_registro` pero en el PDF indican que esté como `btn_Registro` (con R mayúscula) como se ven en la descripción de este tiquete. Se solicita que lo cambies para poder formalizar la entrega de esta actividad.
