### ISSUE TITLE
Punto 8. Agregar un input para ingresar la contraseña

### ISSUE THREAD

**Issue by alvarezjoseud7** [Jose-Moreno/upb-scrum-sprints#7]
### Tareas
+ [x] Agregar etiqueta `<input>`
  + [x] Agregar atributo `id` con valor `“in_contrasena”`

### Resultado esperado
El formulario debe tener un campo `<input>` para ingresar la contraseña, su id debe ser **“in_contrasena”**.

**Comment by Jose-Moreno** [comment]
Implementado en c8e10ab17071ee112a9af3808bce147e3d96a304
