### ISSUE TITLE
Punto 7. Agregar un campo input para ingresar el nombre de usuario

### ISSUE THREAD

**Issue by alvarezjoseud7** [Jose-Moreno/upb-scrum-sprints#8]
### Tareas
+ [x] Agregar etiqueta `<input>`
  + [x] Agregar atributo `id` con valor `“in_nombre_usuario”`

### Resultado esperado
El formulario debe tener un campo `<input>` para ingresar el nombre de usuario, su id debe ser **_“in_nombre_usuario”_**.

**Comment by Jose-Moreno** [comment]
Implementado en c8e10ab17071ee112a9af3808bce147e3d96a304
